version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.4.3
    container_name: elasticsearch_fqab
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
      - "9300:9300"
    stdin_open: true
    tty: true
    restart: 'no'
    networks:
      - es_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.3
    container_name: kibana
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - es_net

  streamlit:
      build:
        context: ./streamlit
      container_name: streamlit
      volumes:
        - ./streamlit:/app
      ports:
        - "8501:8501"
      depends_on:
        - elasticsearch
      networks:
        - es_net

networks:
  es_net: